# Generated by Django 4.0.3 on 2022-06-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itcourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='contacts',
        ),
        migrations.AddField(
            model_name='course',
            name='contacts',
            field=models.ManyToManyField(to='itcourse.contact'),
        ),
    ]
